<a href="https://colab.research.google.com/github/BryceRodgers7/CoTorch/blob/main/BrizzleKNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

## KNN model
url = "https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"

dataset = pd.read_csv(url)

dataset.head()

# all rows, all but last column
X = dataset.iloc[:, :-1].values

# all rows, (last) column #4
y = dataset.iloc[:, 4].values

X.shape
y.shape

# declare test & train sets of data, and same for 'class'
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

# get mean & std of feature data
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# create classifier with k=5, using training feature & class data
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

# make class predictions for test feature data
y_prediction = classifier.predict(X_test)

# see that we have ~90% accuracy, never missed a setosa, most trouble predicting virginicas
print(classification_report(y_test, y_prediction))
print(confusion_matrix(y_test, y_prediction))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         8
  versicolor       0.93      0.87      0.90        15
   virginica       0.75      0.86      0.80         7

    accuracy                           0.90        30
   macro avg       0.89      0.91      0.90        30
weighted avg       0.91      0.90      0.90        30

[[ 8  0  0]
 [ 0 13  2]
 [ 0  1  6]]
