<a href="https://colab.research.google.com/github/BryceRodgers7/CoTorch/blob/main/MyFirstColab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2


4

In [ ]:
import torch
import numpy as np
python_list = [1,2,3,4,5,6,]
python_2darray = [[1,11,12,13,14],[2,21,22,23,24]]

# 2x3 array of random numbers
np1 = np.random.rand(2,3)

# 3x4 tensor of random numbers
tensor_2d = torch.randn(3,4)

# 2x3x4 tensor of all zero's
tensor_3d = torch.zeros(2,3,4)

# default data type for numpy is float64
np1.dtype



dtype('float64')

In [ ]:
# default data type for tensor is float32
tensor_2d.dtype

torch.float32

In [ ]:
# 1-d array, numbers 0 thru 10
tensor1d = torch.arange(11)
tensor1d

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# cut a 1-d array of length 10 into a (2x5) n-dimensional array with same number of elements
ten = torch.arange(10)
newTensor = ten.reshape(2,5)
newTensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# cut a 1-d array length 10 into a 2xm-dimensional array where m yields a matrix with same number of elements
ten = torch.arange(10)
newTensor2 = ten.reshape(2, -1)
newTensor2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# looks like reshape just presents the underlying data differently, so you will have many variables pointing to the same object in memory. Changing one variable changes them all.
ten[2] = 8675309
newTensor2

tensor([[      0,       1, 8675309,       3,       4],
        [      5,       6,       7,       8,       9]])

In [ ]:
# also note that each element in a tensor seems to be a tensor, not a 'number' per se
ten[2]



tensor(8675309)

In [ ]:
newTensor3 = newTensor2.reshape(5,2)
newTensor3
# get the 2nd column of the 5x2 array/tensor, AS A TENSOR
newTensor3[:,1]

#following is not necessarily true lol...
# basic syntax: [ <expressionOfRows> , <expressionOfColumns> ]
# : means 'all rows' or 'from first row until last row' and the ',' separates two expressions in the parenthesis. The last expression specifies which columns, in this case column #1 (0-indexed)

tensor([1, 3, 5, 7, 9])

In [ ]:
# keep the column 'shape' by adding another :
newTensor3[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [ ]:
tensorA = torch.tensor([1,2,3,4])
tensorB = torch.tensor([5,6,7,8])

# add these two tensors (gives same-dimension output)
tensorA + tensorB

# torch namespace '+' operator's definition?
torch.add(tensorA, tensorB)

tensor([ 6,  8, 10, 12])

In [ ]:
# subtraction
tensorB - tensorA
torch.sub(tensorB, tensorA)

tensor([4, 4, 4, 4])

In [ ]:
# naive multiplication??
tensorA * tensorB
# should be same as
torch.mul(tensorA, tensorB)

tensor([ 5, 12, 21, 32])

In [ ]:
# matrix division or naive??
tensorB / tensorA
torch.div(tensorB, tensorA)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# modulus operator gets remainder
tensorB % tensorA
# remainder NOT 'modulus'
torch.remainder(tensorB, tensorA)

tensor([0, 0, 1, 0])

In [ ]:
# naive exponential
torch.pow(tensorA, tensorB)

tensor([    1,    64,  2187, 65536])

In [ ]:
# conveniently all these tensor functions can operate on themselves
tensorA.add(tensorB)
tensorB.div(tensorA)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# extra underscore at the end of these methods means it updates the 'self'
tensorA

tensor([1, 2, 3, 4])

In [ ]:
tensorA.add_(tensorB)

tensor([ 6,  8, 10, 12])

In [ ]:
# notice how this has the same value as the result above: tensorA + tensorB
tensorA

tensor([ 6,  8, 10, 12])